- .gitignore
- crowdin.yml
Add a crowdin CLI config file and support for a gitignored crowdin credentials file.
This will enable us to upload strings to be translated to the new crowdin project here https://crowdin.com/project/curriculumbuilder
> Enable crowdin-cli

- curricula/models.py
- curriculumBuilder/settings.py
- i18n/management/commands/gather_i18n_strings.py
- i18n/models.py
- lessons/models.py
Using the new i18n module, flag some models to be internationalized so we can start syncing their strings up to crowdin.
Depends on https://github.com/mrjoshida/curriculumbuilder/pull/4
> Enable models for i18n

- curricula/models.py
- curriculumBuilder/numbering_patch.py
Cloning (and move operations) were attempting to call lesson renumbering before the unit had been fully saved, and in cases where renumbering was unnecessary. This pulls that behavior, and instead renumbers units when units are cloned (this assumes that lesson numbers shouldn't change when a unit is cloned).
> Fix unit renumbering to fix cloning

- curricula/templates/curricula/curriculum.html
- curriculumBuilder/numbering_patch.py
- static/css/common.css
Adding a two column layout to the course overview page so that the embedded curriculum guide can be shown next to a list of units
> Change course overview page

- curricula/models.py
- i18n/models.py
- lessons/models.py
Specifically, add two things: the ability for Internationalizable models to have some degree of control over the query used to gather their i18n strings, and the ability for them to declare custom logic to determine whether or not any instance should be translated. (the first thing being used to improve the performance of the second thing)
Internationalizable Pages have some default logic by which they recursively walk through their Page-provided `parent` tree, and only consider themselves to be translatable if all of their parents are.
Curriculum elements, being the root thing we want to actually make i18n decisions based on, define their own logic to only whitelist the `csf-1718` curriculum. This method can easily be overwritten in the future as our requirements change.
Finally, Lessons …
> Add I18n whitelist logic

- curricula/admin.py
- curricula/templates/curricula/partials/lesson_front.html
- curricula/templates/curricula/partials/pl_lesson_front.html
- lessons/admin.py
Working through some timeout issues with Dani, it looks like the embedded lessons in the unit edit form were causing issues for units with a lot of lessons (which is the case for most professional learning courses). This does two things - first it drops the embedded lessons from the unit edit page, adds some default ordering to make the multi_lesson batch edit view easier to use, and adds the pacing_weight to the front-end editor for lessons. This should account for the primary use cases for editing lessons from the unit admin.
> Remove batch lessons

- curricula/models.py
Rather than assembling the url with string formatting.
This will be useful when we add locale urls in
https://github.com/mrjoshida/curriculumbuilder/pull/8; specifically, it
will allow a locale-specific version of a page to render locale-specific
links
> Update various get_*_url methods to use reverse

- i18n/models.py
The "elapsed" figure is _slightly_ inaccurate because it does not take into account the amount of time required to resolve the initial `cls.get_i18n_objects()` call (which in the case of things like Activities can be significant) but it's still quite pretty:
> Add pretty output to gather_i18n_strings script

- curriculumBuilder/settings.py
- curriculumBuilder/urls.py
- i18n/urls.py
Enables locale-specific prefixes for homepage and all curriculum routes, to be eventually used for translated content.
After this, you will be able to access the "home page" view at any of:
- https://www.codecurricula.com/
- https://www.codecurricula.com/en-us/
- https://www.codecurricula.com/es-mx/
And similarly, all curriculum content will be accessible at (for example):
- https://www.codecurricula.com/csf-1718/coursea/1/
- https://www.codecurricula.com/en-us/csf-1718/coursea/1/
- https://www.codecurricula.com/es-mx/csf-1718/coursea/1/
Note that this is simply enabling the routes which will eventually be used for localization. Namely, it is _not_ actually translating the content, nor is it enabling the new routes to be published out to S3. Both of those are coming in later PRs.
Open for …
> Enable i18n routes

- i18n/models.py
- lessons/models.py
Depends on https://github.com/mrjoshida/curriculumbuilder/pull/20
Enabling the i18n routes enables the current locale to be set and read from `django.utils.translation`; this PR updates the Internationalizable abstract model to cause all instances of the class to translate themselves based on the current locale as they come out of the database.
Specifically, they do this by grabbing the appropriate i18n file, parsing it as JSON (and caching that result so this process isn't _horribly_ expensive, just somewhat so), and using `setattr` to replace the appropriate field value with the translated result. This is more than a bit clumsy, but it means we get i18n for free without needing to update templates to use internationalizable versions of the fields or perform a migration to replace the …
> render translated content

- curricula/migrations/0027_auto_20180522_1155.py
- curricula/models.py
- lessons/models.py
So units can be manually flagged as ready for internationalization.
Also update the various `should_be_translated` logics to rely on the field. Specifically, curricula are now translated if any of their units have been flagged, and all entities under Unit in the hierarchy (Chapter, Lesson, Activity) are translated iff their Unit is.
> Add i18n_ready field

- templates/basecurriculum.html
There are currently no routes built for the canonical_url, so I'm constructing the link manually for now with django redirects. In the future I want to build out a more robust redirection system for versions.
> Add a banner to old versions of curricula that link to the latest

- .gitignore
- app.json
- crowdin.yml
- curriculumBuilder/settings.py
- i18n/heroku_crowdin.sh
- i18n/models.py
- i18n/sync-down.sh
- i18n/sync-up.sh
Depends on https://github.com/mrjoshida/curriculumbuilder/pull/25
Add two scripts:
- `sync-up` will redact all the i18n source files gathered by `manage.py gather_i18n_sources` and upload the redacted content to crowdin
- `sync-down` will download all (redacted) translations from crowdin, and restore them using the source files.
After both of these scripts have completed successfully, we will probably want to finish by invoking a locale-specific publish operation which will be constructed as a manage.py script. (coming soon in a future PR)
I figure we'll probably want to use something like https://elements.heroku.com/addons/scheduler to run these scripts once a day or so. Thoughts?
> Sync translations with Crowdin

- i18n/models.py
- lessons/models.py
Activities were using their `name` value to build the i18n key, but that's one of the fields on name that actually gets _translated_, which was messing some things up.
To fix it, add a simple process for saving the original, untranslated values when we go through and translate a piece of content, then reference that when building the i18n key.
> Fix activity i18n key

- i18n/utils.py
downgrade "could not find key" log message to debug, since we expect to get it too often for it to be a warning
> Reduce log spam

- bin/sync-i18n.sh
- i18n/management/commands/publish_i18n.py
Adds a new manage.py command `publish_i18n`, the companion to `gather_i18n_strings`. This command will run through all translatable content that has been marked as `should_be_translated` and initiate `publish` and `publish_pdfs` operations for that content if those are available.
> Publish curriculum content in all languages

- curricula/migrations/0028_auto_20180711_1235.py
- curricula/templates/curricula/codestudiolesson.html
- curricula/templates/curricula/lesson-overview.html
- curriculumBuilder/resourcelinks.py
- lessons/admin.py
- lessons/migrations/0038_lesson_opportunity_standards.py
- lessons/models.py
There are some cases where we want to claim a lighter weight standards alignment, which could be better identified as "opportunities for alignment" - specifically when talking about Common Core / NGSS standars in CSF. This adds a separate field to track those standards so that we can call them out as such in lesson plans.
> Standards opportunities

- lessons/admin.py
- lessons/migrations/0039_auto_20180801_1109.py
- lessons/models.py
Adding a list of related lessons to the resource edit view so that we can more easily track down all of the places a resource is linked to a lesson. Note that this doesn't account for cases where a writer references a resource by md tag (eg `[r resource-slug]`), only where they've properly attached the resource to the lesson.
> List related lessons on resource edit view

- lessons/admin.py
- lessons/migrations/0040_resource_force_i18n.py
- lessons/models.py
Specifically, sync with Crowdin those Resources that are associated with a Lesson that is also being synced, which will cover the 180 Resources that are currently explicitly associated with a CSF lesson.
Also provide an override flag so we can manually enable additional Resources. Say, for example, those Resources that are included merely as markdown links.
> enable Resources for translation

- curricula/templates/curricula/codestudiolesson.html
- curricula/templates/curricula/pl_lesson.html
To ensure that they link to the locale-specific version of the standards when in locale mode
> Update a couple links to use get_standards_url rather than assembling it manually

- curricula/templates/curricula/partials/code_studio.html
- curricula/templatetags/level_embed.py
A while back a change was introduced to levelbuilder that restructured embedded map levels so that they could be accessed from studio.code.org instead of curriculum.code.org. This broke our ability to load those embedded levels in the code studio pullthrough because we are unable to load studio.code.org urls in an iFrame. Ideally I'd like to resolve this such that we aren't restructuring these urls on both sides, but for now this is necessary to fix the code studio pullthrough.
> Restructure URLs for level embedding

- curricula/models.py
- curricula/templates/curricula/partials/lesson_pills.html
- curricula/templates/curricula/partials/unit_pills.html
Compiled resource PDFs have been broken in CSF for a while now and we receive consistent tickets about it. Removing the link until I have time to figure out the root cause.
> Remove "All Handouts PDF" link from CSF

- curricula/models.py
- curricula/templates/curricula/curriculum.html
- curricula/templates/curricula/unit.html
- curricula/views.py
- documentation/models.py
- lessons/models.py
The inital cloning feature assumed that we are always cloning with all children. In reality, it's more reasonable to clone the course empty and then pull in a clone of each unit one at a time as we are prepared to write them. This first step adds a checkbox to exclude children while cloning. Still ToDo:
* Pull out admin pane into a partial template
* Pull out admin js into a separate file
* Add dropdown to clone a unit into a different course
> Add option to exclude children when cloning.

- curricula/serializers.py
- curricula/urls.py
- curricula/views.py
- lessons/models.py
The OneNote team needs to consume a json file to generate course specific OneNote folders. So far they've been using the same json that we publish for Code Studio, but want to attempt importing our activity guide content directly. This pulls in the HTML from gdoc activitiy guides and sanitizes it according to the OneNote requirements.
> Onenote json

- curricula/migrations/0029_auto_20190110_1507.py
- curricula/models.py
- lessons/migrations/0041_auto_20190110_1507.py
- lessons/models.py
We're restructuring the teacher forum, which means that the current lesson forum link structure no longer works. This introduces a couple of new fields on the unit that allow for each unit to have a unique forum link structure to allow for differences between units where we want to direct to a lesson specific tag vs those that should link to a broader topic (like the PT prep unit).
> Custom forum link structuring per unit

- i18n/heroku_crowdin.sh
We use [heroku scheduler](https://scheduler.heroku.com/dashboard) to automate the i18n sync, but it's been broken for a while now.
Turns out, this is because when running tasks through scheduler, the environmental variable `JAVA_TOOL_OPTIONS` is set to `-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=1098 -Dcom.sun.management.jmxremote.rmi.port=1099 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.local.only=true -Djava.rmi.server.hostname=172.17.169.146 -Djava.rmi.server.port=1099`, which causes our (pretty damn hacky) custom java invocation of the crowdin cli to break.
Note that this environment variable is _not_ set when running commands with `heroku run`, which is why the manual sync has …
> fix automatic i18n sync

- i18n/models.py
[Jira task](https://codedotorg.atlassian.net/secure/RapidBoard.jspa?rapidView=28&projectKey=FND&view=detail&selectedIssue=FND-33)
I originally set out to translate `content` _instead of_ `description`, but upon closer investigation it turns out that we do in fact want to translate both of them.
Both content and description are fields provided by Mezzanine; by default, `description` will be generated from (and therefore be identical to) `content`, but it's possible to override that so the fields are distinct. We do actually take advantage of this optional feature in a couple cases, so we want to translate both fields just in case.
This does mean that any objects that do _not_ override `description` will upload identical strings for both content and description, but fortunately Crowdin …
> include Mezzanine 'content' field for all internationalized Page models

- documentation/admin.py
- documentation/urls.py
- documentation/views.py
At some point recently the documentation routes stopped working. This was likely caused by some of the changes I made to move map levels into docs.code.org. This corrects for that issue as well as fixing a long standing bug that prevented the admin "view on site" button from using the correct local route for ides and blocks
> Fix documentation url routing

- i18n/heroku_crowdin.sh
the installation path of the crowdin-cli.jar changed in apt, so update the hacky script we use to run it to match
> fix crowdin script

- lessons/static/css/commonlesson.css
Add a white background to display of mini rubric in code studio pull through because I forgot to commit this one line on my last PR (https://github.com/mrjoshida/curriculumbuilder/pull/70). Image of what it looks like can be found there.
> White background for Mini Rubric Display

- curricula/templates/curricula/partials/code_studio.html
- lessons/static/css/commonlesson.css
Add a border to assessment icon to make it stand out more when the tab is selected.
Update icons to make code studio and curriculum builder use a consistent set of icons.
**Issue:** Still have not figured out the bug that is causing icons to show up as empty boxes. Plan to work with Josh later this week on it.
> Updating Level Icon Set and Add White Border on Assessment Icon

- curricula/templates/curricula/partials/code_studio.html
- curricula/templates/curricula/partials/unit_calendar.html
- lessons/static/css/commonlesson.css
- static/css/common.css
> Level icons now show the icon instead of a blank square

- curricula/templates/curricula/partials/compare.html
- templates/accounts/account_login.html
- templates/accounts/account_password_reset.html
- templates/accounts/account_profile.html
- templates/accounts/includes/user_panel.html
- templates/admin/change_form.html
- templates/includes/editable_toolbar.html
- templates/index.html
This PR removes the translation tags from a number of strings. I've manually tested all the ones I could find, but I couldn't always figure out the path to these views (I wouldn't be surprised if some of these aren't used).
> Remove some template translations

- curricula/models.py
- curricula/views.py
- documentation/models.py
- i18n/management/commands/publish_i18n.py
- lessons/models.py
First step in adding better error logging to the i18n sync: clean up the existing logs.
Right now, the i18n sync is _super_ noisy in slack, because every single piece of content published (in every single language) gets logged. This adds some logic to the publish operation to conditionally silent logging, and uses that in the i18n sync to only log high-level overviews of what gets logged. This should make the logs more useful to actually parse.
Next step: add error detection and logging.
> Make the i18n sync slack logs quieter and more informative

- i18n/management/commands/i18n_sync_down.py
- i18n/management/utils.py
Log the lists of translation files and languages individually, rather than logging the cross product.
Also add logging for missing files.
> make the i18n sync down a little less verbose

- curricula/models.py
- i18n/management/commands/publish_i18n.py
- i18n/management/utils.py
1. They're broken for English and non-English
2. They don't seem to be used anywhere (and there's no UI element that directs you to them, unlike the courses)
There are still some courses where PDF generation fails (Course D and Express in particular) due to a faulty link in some content. However, the publish command does continue locally, unlike on the Dyno, and I have a theory it's due to a timeout as it would try to publish CSF-1718 next, which is *large*.
~This PR also prevents us from syncing in-tl, which I don't believe we need to be generating.~
> Don't try to publish PDFs for Curriculum

- templates/generic/includes/rating.html
- templates/includes/editable_form.html
- templates/includes/form_errors.html
- templates/includes/pagination.html
- templates/includes/search_form.html
- templates/pages/menus/admin.html
- templates/pages/menus/dropdown.html
- templates/pages/menus/footer_tree.html
- templates/pages/menus/mobile.html
- templates/pages/menus/primary.html
- templates/pages/menus/tree.html
I've played around on the site a bit and haven't seen any issues. These are all straightforward tag changes.
> Remove translation tags in templates/generic/includes and templates/pages/menus

- i18n/management/commands/i18n_sync_down.py
Follow-up to https://github.com/mrjoshida/curriculumbuilder/pull/85
The goal of that PR was to only redact content we know we want to be
redacted, to prevent applying markdown formatting to things we don't
want to treat as markdown (like Resource URLs). Unfortunately, even
though we're only _redacting_ the things we know we want to process,
we're still _restoring_ everything, which applies the same formatting as
redaction.
Extending the requirement to both redaction and restoration should
actually fix the problem.
Also broke the `handle` method up into individual helper methods, since
it was getting too long.
> Only restore redacted content

- curricula/templates/curricula/partials/code_studio.html
- lessons/static/css/commonlesson.css
> Code Studio Pull Through: Fix mini rubrics showing up on non-mini-rubric levels.

- curricula/templates/curricula/partials/lesson_front.html
Assessment Opportunities Area was getting too long for the right column so Curriculum asked that it be moved to the left column.
> Lesson Front Page: Move assessment opportunities area to left column

- curricula/templates/curricula/partials/code_studio.html
- lessons/static/css/commonlesson.css
- templates/basecurriculum.html
- templates/cdo_base.html
Rolls us back to Font Awesome Version 4.6.3 to match Code Studio. (Reverses the work of this commit: https://github.com/mrjoshida/curriculumbuilder/commit/7023033ac29a5950a0e0ff1fc1ff9c9baa0129a8)
By rolling back to the earlier version of Font Awesome we can use the external-link icon again. This also sets it up with the styling we needed to do so it would not show as a blank square.
> Font Awesome Version 4.6.3 and View on Code Studio Icon

- lessons/models.py
Follow-up for #98, which did not account for levels that have multiple XML blocks in their long_instructions.
This level has 2 blockly XML blocks:
"blocks to the bottom of the" (text between the two XML blocks) is missing:
"blocks to the bottom of the" (text between the two XML blocks) is present:
> Refactor parsed_long_instructions to account for multiple XML blocks

- curricula/templates/curricula/partials/code_studio.html
> Remove extra < that is showing on teacher overview tab

- Aptfile
Used by the Django translation system, added in
https://github.com/mrjoshida/curriculumbuilder/pull/74
> Add gettext to the heroku dynos

- Aptfile
- app.json
Followup to https://github.com/mrjoshida/curriculumbuilder/pull/109
> Enable gettext as a buildpack, rather than from apt

- i18n/config/crowdin.yml
- i18n/management/commands/i18n_sync_down.py
- i18n/management/utils.py
- i18n/utils.py
In https://github.com/mrjoshida/curriculumbuilder/pull/74, we updated the locations of the translations files for the sync in and down, but needed to also update the other parts of the sync out (ie, restoration and uploading).
In part, that was because we were manually specifying the location of the i18n files in several locations; I've updated all these to use the new I18nFileWrapper.locale_dir method, which should mean that future changes of this nature only have to happen in one place.
I also removed the `languages_mapping` in the crowdin config, since it appears that the `locale_with_underscore` settings means that crowdin does, in fact, use the four-character version
> use locale_name for sync out

- i18n/config/crowdin.yml
For some reason, when downloading translations using
locale_with_underscore, crowdin correctly uppercases the locale for all
languages EXCEPT the pseudo-language we use to enable in-context
translations. So we have to manually coerce it to the right format.
> Fix capitalization of in-context-translation pseudo-language

- i18n/config/crowdin.yml
1. The languages mapping was added as a separate "files" entry, rather
than being added as an element of the existing "files" entry
2. The key for the language mapping should be the shortcode, not the
long
> Fix mistakes in crowdin config file

- curricula/templates/curricula/partials/code_studio.html
Update the level pull through to pull through using the new way we are saving performance level values.
ore
> Mini Rubric: Performance Level Naming Clean Up

- curricula/templates/curricula/partials/code_studio.html
Now that a named level can also be an assessment level we need to indicate that correctly in the code studio pull through.  Below is what it ends up looking like.
> Show assessment icon in the correct place for named assessment levels

- lessons/models.py
The table of contents is pulled dynamically from the page markup after the page loads. The header itself is constructed here:
https://github.com/mrjoshida/curriculumbuilder/blob/a2195cda812910c2420c6b9510e11d38234a490e/lessons/models.py#L123
> Translate resource types

- lessons/static/css/commonlesson.css
partially addresses [LP-180](https://codedotorg.atlassian.net/browse/LP-180)
Specifically, makes it so that instructions content can be excluded from code studio pull-through into curriculumbuilder via the `.no-pullthrough` css class.
> hide instructions content via .no-pullthrough

- curricula/templates/curricula/partials/code_studio.html
Remove 2019 restriction on assessment design to match removing the flag on code studio.
This impacts the Code Studio Pull-Through. We will now show the assessment marker on any level marked as an assessment in any course. We will also show the mini rubric for any level that has a mini rubric.
> Assessment and Mini Rubric: Release to All Courses

- curricula/templates/curricula/partials/code_studio.html
This fixes [LP-380](https://codedotorg.atlassian.net/browse/LP-380) and [LP-258](https://codedotorg.atlassian.net/browse/LP-258).
Level group levels were not pulling through. Now we give a message that to view a level group you should head to Code Studio.
Contained levels where marking answers as right or wrong which would give away the answer if a student were to find the lesson plans.  Instead we now just don't show which one is right or wrong!
We just had a bug here where we were not doing the pull through for named levels and other levels the same. Updated the non-named levels to match the way we were using for named levels (which was working)
> Code Studio Pull Through: Contained Levels and Map Levels Fix

- curricula/serializers.py
- i18n/models.py
- lessons/models.py
Allow iterable fields to be added to `internationalizable_fields` (provided a matching serializer). Sample source/Lesson.json:
```js
"coursee/introduction-course-warm-up": {
"cs_content": "We recognize that every classroom has a spectrum of understanding for every subject. Some students in your class may be computer wizards, while others haven't had much experience at all. In order to create an equal playing (and learning) field, we have developed this \"Ramp-Up Stage\" for Course E. This can be used as either an introduction or a review to the Code.org interface and basic computer science concepts. This stage, along with the three that follow, cover all prerequisites needed to start Course E.", 
"description": "This lesson will give you practice in the skills you will need for this …
```
> Keywords i18n serializer

- lessons/migrations/0043_auto_20190520_1630.py
- lessons/models.py
Sample from source/Vocab.json:
```js
"command": {
"detailDef": "An instruction for the computer. Many commands put together make up algorithms and computer programs. ", 
"simpleDef": "An instruction for the computer. Many commands put together make up algorithms and computer programs. ", 
"word": "Command"
}, 
"condition": {
"detailDef": "A statement that a program checks to see if it is true or false.  If true, an action is taken. Otherwise, the action is ignored.", 
"simpleDef": "Something a program checks to see if it is true before allowing an action.", 
"word": "Condition"
}, 
"conditionals": {
"detailDef": "Statements that only run under certain conditions.", 
"simpleDef": "Statements that only run under certain conditions.", 
"word": "Conditionals"
}, 
```
Most of the short/long …
> Make `Vocab` a translatable model

- curricula/models.py
- curricula/templates/curricula/partials/lesson_pills.html
- curricula/templates/curricula/partials/unit_pills.html
Lesson plan and handout PDF links for CSF-19 currently dead end on a "Requested Page Not Found" page because there is a problem with PDF generation. 
The Learning Platform team is tracking a deeper investigation and longer term fix for PDF generation issues ([LP-545 ](https://codedotorg.atlassian.net/browse/LP-545)). 
In the meantime, I've removed the Lesson PDF and Handouts PDF links for Express & Pre Express 2019. 
BEFORE:
AFTER:
> Hide pdf links for lessons and handouts for csf-2019

- i18n/models.py
- i18n/tests/models.py
- i18n/tests/test_internationalizable.py
- i18n/utils.py
Since our i18n values are communicated through JSON, we always want to
use strings. Using non-string values will work fine for source string
generation, since the keys will be converted to strings in the
serialization process; but it will fail to find the translations since
the string keys won't be converted back to integers in the
deserialization process.
> Use strings for i18n keys

- curricula/models.py
- curricula/templates/curricula/partials/lesson_pills.html
- curricula/templates/curricula/partials/unit_pills.html
Reverts mrjoshida/curriculumbuilder#133
PDFs are working for Express and Pre-Express 2019 now, so reverting this PR to unhide the "Handouts PDF" link for these.
> Revert "Hide pdf links for lessons and handouts for csf-2019"

- curriculumBuilder/resourcelinks.py
Prior behavior was to either not render a section that included broken resources, or fail to load the page entirely. Merging ASAP to unblock PL.
> Fail visibly when resource not found

- lessons/models.py
By speeding up the query that gathers the model objects
Vocab: complete (92.30 elapsed, 0.3961 average)
Vocab: complete (0.01 elapsed, 0.0001 average)
> speed up gathering of vocab strings

- .travis.yml
Fixes https://codedotorg.atlassian.net/browse/LP-666
The problem was pycurl failing to install: https://stackoverflow.com/questions/46290556/installing-pycurl-with-fatal-error-gnutls-gnutls-h-no-such-file-or-directory
> install libgnutls28-dev before requirements.txt

- curriculumBuilder/settings.py
heroku deploys are failing with this error:
```
redis_url = urlparse.urlparse(os.environ.get('REDIS_URL'))
AttributeError: 'function' object has no attribute 'urlparse'
```
https://github.com/mrjoshida/curriculumbuilder/blob/d4794440962f4ab8fc90b3812e08b65d2fc55e57/curriculumBuilder/settings.py#L232
@bethanyaconnor tracked it down to this PR: https://github.com/mrjoshida/curriculumbuilder/pull/144
> fix syntax for importing and calling urlparse

- .travis.yml
- curricula/tests.py
- curricula/tests/test_curricula_rendering.py
- curricula/tests/test_iframe.py
Add a few tests which render various views under `curricula/`. This PR does the minimum in each test needed to get code coverage numbers up, which is an important metric for when we are ready to move to python 3.
This increases our coverage within `curricula/` from 4% to 57%, and increases our overall coverage from 17% to 40%.
New coverage report: [cb-coverage-report-02.txt](https://github.com/mrjoshida/curriculumbuilder/files/3618099/cb-coverage-report-02.txt)
> Test curricula rendering routes

- i18n/tests/test_internationalizable.py
A small tweak to i18n tests allows them to pass when the `--keepdb` flag is specified, which reduces the amount of time it takes a developer to run all unit tests locally from 1m23s to 23s.
```
(cb) Dave-MBP:~/src/cb (keepdb-i18n)$ time debug=true ./manage.py test --keepdb
Using existing test database for alias 'default'...
...
Ran 933 tests in 5.102s
OK
Preserving test database for alias 'default'...
real	0m23.131s
user	0m21.181s
sys	0m2.393s
```
Test cases which derive from Django's `TestCase` already wrap DB activity in a transaction, eliminating the need to explicitly clean up.
> Clean up between i18n tests

- standards/admin.py
- standards/models.py
The new CSP framework has introduced some issues in our import/export system due to duplicate shortcodes used in both the older and newer framework. This addresses that by forcing the import mechanism to lookup categories by both shortcode and framework
> Category / Standards import/export improvements

- documentation/templates/documentation/block.html
- documentation/templates/documentation/embed.html
- documentation/templates/documentation/map.html
- static/cdo/js/applab-docs.js
[LP-287](https://codedotorg.atlassian.net/browse/LP-287): We're seeing an issue where CodeMirror is applying incorrect spacing to HTML snippets only when the page is rendered within an iframe on a Code Studio map level.  This seems to be due to a timing issue - the CodeMirror handler is being invoked before the document in the iframe has fully loaded, leading to some incorrect calculations.
| [Embedded](https://studio.code.org/s/csd2-2018/stage/6/puzzle/6) | [Not Embedded](https://studio.code.org/docs/concepts/html/lists/index.html) |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/1615761/65471506-2e63eb80-de24-11e9-9551-25c238ea045a.png) | ![image](https://user-images.githubusercontent.com/1615761/65471516-3a4fad80-de24-11e9-894a-64774416c521.png) |
Here I'm …
> Invoke CodeMirror later on certain pages

- curricula/urls.py
- curricula/views.py
This route appears to be unused because (1) @mrjoshida says it is, but also because (2) there are no references to it either via urls ending in `/pdf/` or `/pdf`, or via url helpers like this one which points to a different route: https://github.com/mrjoshida/curriculumbuilder/blob/08ae80dfed1f9b66f95f16d8d1925fc28443e472/curricula/models.py#L82-L84
> remove unused lesson_pdf routes

- documentation/templates/documentation/partials/block.html
Per request by @mikeharv this hides the type and required columns in the parameters table for blockly documentation (currently only Sprite Lab). See https://docs.google.com/document/d/1vIw33WKqzlDm3SXyFKRXraIRCiXtCQ1m7ylUQv7UIcA/edit#heading=h.ijnjwv3fic1e
> Display properties differently for blockly based tools

- requirements.txt
Previously, installing pycurl on Mac OS resulted in an error which is documented here: https://github.com/code-dot-org/curriculumbuilder/commit/98ceaffc5568b3f03c116de515e72943be931912#diff-04c6e90faac2675aa89e2176d2eec7d8R83-R85
This does not appear to be a problem in the latest version of pycurl.
Manually verified via the following steps:
```
pip uninstall pycurl
rm -rf ~/Library/Caches/pip # clear pip cache on Mac OS
rm -rf ~/.cache/pip # clear pip cache on Ubuntu
pip install -r requirements.txt
debug=true python manage.py runserver_plus
```
http://localhost:8000/
> upgrade pycurl to avoid openssl problems

- curricula/templates/curricula/chapter.html
- curricula/templates/curricula/unit.html
- curricula/templates/curricula/unit_glance.html
- curricula/templates/curricula/unit_lessons.html
https://codedotorg.atlassian.net/browse/FND-679
The Lesson 1, Lesson 2, etc headers on the Curriculum Builder pages were not being translated (see JIRA for screenshot). I found the original reported String and a few other's which matched it and decided to add translations for them all.
* Verified page still showed Lesson 1, Lesson 2, etc
`debug=true python manage.py runserver_plus`
* Found the following entry in `i18n/static/source/django.po` after running `bin/sync-i18n.sh`
``` python
#: curricula/templates/curricula/chapter.html:102
#: curricula/templates/curricula/unit.html:120
#: curricula/templates/curricula/unit.html:211
#: curricula/templates/curricula/unit_glance.html:92
#: curricula/templates/curricula/unit_glance.html:138
#: curricula/templates/curricula/unit_lessons.html:81
#: …
```
> Add translation support for "Lesson N" headings

- i18n/models.py
Partially to save time, partially so we don't attempt to divide by zero later: https://github.com/code-dot-org/curriculumbuilder/blob/4fa9f93c7c6637c9fae3dcdceaa01a79c7f33873/i18n/models.py#L75
> don't attempt to gather strings if there are no objects to gather from

- bin/sync-i18n.sh
- i18n/management/commands/log_i18n_failure.py
- i18n/management/commands/log_i18n_success.py
Previously, we just logged each step of the i18n sync individually, including an indication that all steps had finished. The problem with that is of course that if all steps _didn't_ finish, you have to be paying explicit attention to notice.
This adds a more explicit error message when anything goes wrong.
> improve i18n sync error messaging

- i18n/models.py
So we don't crash when trying to gather strings for models that have a large number of iternationalizable objects.
See https://docs.djangoproject.com/en/1.8/ref/models/querysets/#iterator and https://blog.etianen.com/blog/2013/06/08/django-querysets/ for more information
> Use queryset iterator to gather i18n strings

- lessons/migrations/0044_auto_20191021_1519.py
- lessons/migrations/0045_auto_20191022_1419.py
- lessons/models.py
- standards/migrations/0007_auto_20191021_1519.py
migrations for https://github.com/code-dot-org/curriculumbuilder/pull/168 . See that PR for context.
> Vocab migrations

- lessons/admin.py
- lessons/models.py
partially addresses [LP-829](https://codedotorg.atlassian.net/browse/LP-829). Limits access for anyone without the `access_all_vocab` permission to only be able to view, change or delete vocabs which they own. the migrations which set us up for this will be ship ahead of this PR in #169. 
This solution relies on the [Ownable](http://mezzanine.jupo.org/docs/packages.html#mezzanine.core.models.Ownable) and [OwnableAdmin](http://mezzanine.jupo.org/docs/packages.html#mezzanine.core.admin.OwnableAdmin) classes in mezzanine, which is the CMS currently used by django to manage page hierarchy. It also relies on the existing user/group permissions model built into django.
This breaks down as follows:
* `Ownable` assigns every object an owner, which by default is whoever created it
* `OwnableAdmin` …
> Filter vocab admin view for partners to those owned by current user 

- curricula/migrations/0031_auto_20191023_1350.py
- curricula/models.py
- curricula/tests/test_curricula_rendering.py
- lessons/migrations/0046_auto_20191023_1357.py
- lessons/models.py
- standards/tests.py
migrations for https://github.com/code-dot-org/curriculumbuilder/pull/172 . See that PR for context.
> add owner field and access_all permission to other models

- lessons/admin.py
- lessons/models.py
Quick fix for two problems on the lesson edit page introduced in https://github.com/code-dot-org/curriculumbuilder/pull/173, namely that you can't add an objective or activity. see error here: 
The [InlineModelAdmin](https://docs.djangoproject.com/en/2.2/ref/contrib/admin/#django.contrib.admin.InlineModelAdmin) class used to insert the editors for objectives and activities into the lessons page doesn't have a great way to insert a default value for the user_id, so I couldn't easily copy the approach used by [OwnableAdmin](http://mezzanine.jupo.org/docs/_modules/mezzanine/core/admin.html#OwnableAdmin) .
> fix lesson page inline editors

- lessons/models.py
https://github.com/code-dot-org/curriculumbuilder/pull/173 broke curriculum team's ability to edit lesson plans inline. this is a temporary fix to unblock them.
> override Ownable and allow inline editing of lessons

- curriculumBuilder/local_settings.py.example
these changes are needed in local_settings.py in order for Linux setup instructions to work, and adding them doesn't seem to break running the local server on Mac, so rather than adding another step to the setup it seems best to just include these in the local settings file which is already copied into place during existing setup steps.
> add linux-friendly database config to local settings example

- lessons/admin.py
The admin pages for `Objective` and `Activity` have a dropdown to assign the object to a lesson. We want to make sure that partners can only assign these objects to their own lessons. I did not see an easy way to filter what shows up in the menu, but I did figure out how to reject the request if they select a lesson which does not belong to them:
I got the idea to override `save_form` because I saw that that's what the `OwnableAdmin` class overrode to accomplish custom behavior when an object was being updated: http://mezzanine.jupo.org/docs/_modules/mezzanine/core/admin.html#OwnableAdmin
It's not the best UX, because it lets partners select a bad value and then gives an ugly exception. But it will at least keep their data in a good state.
> Limit what partners can select in lesson dropdowns

- curricula/models.py
- lessons/models.py
https://github.com/code-dot-org/curriculumbuilder/pull/173 added `Ownable` as a parent to several models, which broke inline editing because it overrode `is_editable` to ignore our existing `change_*` permissions.  A quick fix for this was made to `Lesson` and `Activity` (removed in this PR), to allow curriculum team members to regain inline editing privileges. However the following two problems remain:
1. partners (who do not have `access_all_*` permissions) **can** currently inline-edit any `Lesson` and `Activity` objects
2. curriculum team (who have `access_all_*` permissions) **cannot** currently inline-edit any `Curriculum` or `Unit` objects
This PR does the following:
1. extracts a `Filterable` interface which overrides `is_filterable` for all `Ownable` models
2. implements correct …
> extract and implement Filterable class in Ownable models

- curricula/templates/curricula/codestudiolesson.html
- curricula/templates/curricula/hoc_lesson.html
- curricula/templates/curricula/partials/admin_menu.html
- curricula/tests/test_curricula_rendering.py
- curricula/views.py
In response to bug bash feedback, this PR hides the admin controls in the settings menu for partners who are viewing a page which they do not own. This includes the following buttons: Publish, Publish PDFs, Clone,  Get Code Studio Stage Details.
The Resources and Vocab sections are preserved, because those are useful when viewing lessons you don't own.
lesson | hoc lesson
--- | --- 
lesson | hoc lesson
--- | ---
> Hide admin controls from partners on pages they do not own

- .github/pull_request_template.md
Elijah added a PR template to the normal code repo: https://github.com/code-dot-org/code-dot-org/pull/30930
This adds that PR template to Curriculum Builder.
> Add the PR Template to Curriculum Builder

- templates/403.html
This makes it so that when Broward clicks these links on pages they don't own, they'll be taken to codecurricula.com/admin instead of studio.code.org/courses:
docs on django error views can be found here: https://docs.djangoproject.com/en/2.2/ref/views/#error-views but basically the existing 403.html file is the default location for the error template that gets rendered when a permission denied error occurs. `request` is the only accessible object in that view, unless you define a custom `handler403` view.
> send staff users to /admin on 403

- curricula/factories.py
- curricula/tests/test_curricula_rendering.py
- lessons/factories.py
- requirements.txt
extracting factories for django model classes via [factory boy](https://factoryboy.readthedocs.io/en/latest/introduction.html) turned out to be a piece of cake once I realized that I needed to use their `factory.django.DjangoModelFactory` class instead of their more general `factory.Factory` class. I mostly followed these recipes: https://factoryboy.readthedocs.io/en/latest/recipes.html one gotcha is also documented inline.
This should set us up well to add more tests around permissions without so much setup code bloat.
> extract factory classes from curricula rendering tests

- LICENSE
This adds the same LICENSE we have on our code-dot-org repo to curriculum builder.
We need the approval of everyone who has contributed to the repo in order to add this so please review if you are tagged.
> Add LICENSE to curriculumbuilder

- lessons/admin.py
- lessons/tests.py
- lessons/tests/test_lessons_admin.py
Yesterday's bug bash revealed that there are many fields we want to hide from platformization partners such as Broward. 
Hide the Force I18n field from the Resource admin page for users without the `access_all_resources` permission. As noted in comments, this permission now serves as a proxy for what might better be named "administer resources". The plan is to hold off on renaming it until we see what our other needs might be as Broward starts to work with Curriculum Builder.
The following docs show APIs related to dynamic fields and fieldsets:
https://docs.djangoproject.com/en/1.8/ref/contrib/admin/#django.contrib.admin.ModelAdmin.get_fields
https://docs.djangoproject.com/en/1.8/ref/contrib/admin/#django.contrib.admin.ModelAdmin.get_fieldsets
Unfortunately, certain related methods such …
> Filter privileged resource fields

- lessons/admin.py
- lessons/tests/test_lessons_admin.py
Follow-on to https://github.com/code-dot-org/curriculumbuilder/pull/187 . Hides the "Hidden" field from the Lesson admin page. Uses fieldsets instead of fields.
New unit tests added to verify contents of lesson admin page with and without access_all permissions.
> Filter privileged fields on lesson admin page

- curricula/templates/curricula/curriculum.html
- curricula/templates/curricula/pl_curriculum.html
- curricula/templates/curricula/pl_lesson.html
- curricula/templates/curricula/pl_unit.html
- curricula/templates/curricula/unit.html
- curricula/views.py
https://github.com/code-dot-org/curriculumbuilder/pull/183 hid the admin menu (publish button, etc) for partners on lesson pages, while continuing to allow authors with `access_all` permissions to publish. Unfortunately, this hid the admin controls (including publish button) for all users on curriculum pages, unit pages, and PL lesson pages. This PR fixes that regression by restoring access to the admin controls for authors while continuing to hide them for partners.
The original PR contained unit tests. This PR does not contain tests because the fix is needed somewhat urgently by the PL team. similar unit tests will be added in the next PR. For now, I have manually verified that the Publish button has appeared locally on curriculum and unit pages whereas it is not visible on the same …
> Fix regression which caused publish button to disappear

- README.md
- requirements.txt
Eliminates the following warning when building and running curriculumbuilder:
> /app/.heroku/python/lib/python2.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
In addition to running existing unit tests, I've made sure the server can be run and accessed locally on both Mac and Linux.
> upgrade psycopg2 to avoid build warning

- curricula/templates/curricula/hoc_lesson.html
- curricula/templates/curricula/partials/admin_menu.html
- curricula/tests/test_curricula_rendering.py
Follow-on to https://github.com/code-dot-org/curriculumbuilder/pull/195, which was merged without tests to unblock the PL team. This PR extracts some test helpers and adds test cases to cover the code changes in #195 . 
update: this PR also omits Get Code Studio Stage Details from the menu for users who do not have permission to edit the page.
Adds unit test cases for each unique way that we render the admin menu.
> add unit tests for admin menu, and omit more controls

- curriculumBuilder/settings.py
- curriculumBuilder/tests/test_richtext.py
To prevent translators from embedding unwanted content using those tags.
To verify that this won't break any existing content, I:
1. set
```
JACKFROST_STORAGE = 'jackfrost.defaults.JackfrostFilesStorage'
```
in `local_settings.py`
2. ran
```python
from curricula.models import Curriculum
for curriculum in Curriculum.objects.all():
if curriculum.jackfrost_can_build():
list(curriculum.publish(True))
```
3. used `grep -Ro "<object" __jackfrost` to find all examples of `<object>` tags in content
4. verified that only [`csf-18/index.hml`](https://www.codecurricula.com/csf-18/) was using an object tag, and that was to embed https://code.org/curriculum/docs/csf/CSF_Curriculum_Guide_2018_smaller.pdf on the page
5. with assistance from Mike and Arron, updated the page to instead embed …
> remove 'object' from the list of tags allowed in markdown

- curricula/tests/test_curricula_admin.py
- lessons/tests/test_curricula_admin.py
Limited so fields of the edit page for external accounts in this PR: https://github.com/code-dot-org/curriculumbuilder/pull/194/. This is the follow-up work to add the tests for that.
> Add unit tests for unit and curriculum edit pages

- curricula/templates/curricula/partials/hoc_lesson_front.html
- curricula/templates/curricula/partials/lesson_front.html
- curricula/templates/curricula/partials/pl_lesson_front.html
Hide the Add Resource Button on Lesson Front End unless you are a superuser since only superusers have permissions to see the page that link takes you to.
| Superuser | Non-Superuser |
| --- | --- |
| ![Screen Shot 2019-11-22 at 3 00 52 PM](https://user-images.githubusercontent.com/208083/69456592-0700a080-0d39-11ea-808f-fd38e1887831.png) | ![Screen Shot 2019-11-22 at 3 01 19 PM](https://user-images.githubusercontent.com/208083/69456590-06680a00-0d39-11ea-96cc-8a42b43c25e0.png) |
- [jira](https://codedotorg.atlassian.net/browse/LP-894)
> Hide add resource button unless you are a superuser

- curricula/urls.py
Issue: 
- Go to : https://studio.code.org/s/csd4-2019/stage/12/puzzle/13
- Go to help and tips tab
- Click on Design Mode
- In pop up right click on one of the things in the left nav bar
- Page gives error
- In url add `docs/` in front on concepts
- No more page error
I think this is the fix to fix the code studio problem described above but I don't know of any way to confirm that it works without just shipping it.  Thoughts?
- [jira](https://codedotorg.atlassian.net/browse/LP-910)
> Use docs/concepts instead of just concepts

- documentation/models.py
- documentation/templates/documentation/partials/map_menu.html
- documentation/templatetags/documentation_extras.py
- documentation/tests/test_map_model.py
Still trying to solve the same problem explained here: https://github.com/code-dot-org/curriculumbuilder/pull/204
Except now we know curriculum.code.org needs the links to be '/documentation/concepts...' and studio.code.org needs the links to be '/docs/concepts..'
This is definitely a temporary solution and we are tracking the need to clean up all of this here: https://codedotorg.atlassian.net/browse/LP-1072
- [jira](https://codedotorg.atlassian.net/browse/LP-910)
Updated the tests to match the new functions.
> Give a different url depending on the host

- documentation/templatetags/documentation_extras.py
When I tried to publish a map I got a bunch of no know host errors that said the host was testserver (https://codedotorg.slack.com/archives/C0SUN2VT5/p1576181556149800). Going to add testserver here and see if that fixes things.
> Add testserver as a host

- curriculumBuilder/urls.py
- curriculumBuilder/views.py
- documentation/admin.py
- documentation/templates/documentation/map.html
- documentation/templates/documentation/pages.html
- documentation/templatetags/documentation_extras.py
- documentation/tests/test_map_model.py
Continuing of #210 and #211.
This changes localhost, curriculum.code.org, and codecurricula.com to user /docs instead of /documentation. /documentation will still work tho if someone has an old link to it. This is one of two steps in getting all the urls for documentation closer to using the same paths.
Next will be figuring out how to make docs.code.org use the same pattern as well.
- [jira](https://codedotorg.atlassian.net/browse/LP-910)
Still haven't figured out the best way to test this all yet.
> Use /docs instead of /documentation for links

- curricula/urls.py
- documentation/templatetags/documentation_extras.py
- documentation/tests/test_map_model.py
Need the www.codecurricula.com as a host for menu to work.
Also make docs.code.org/docs and docs.code.org both go to the same place.
> Add www.codecurricula.com back

- curriculumBuilder/urls.py
- documentation/admin.py
- documentation/templates/documentation/map.html
- documentation/templates/documentation/pages.html
- documentation/templatetags/documentation_extras.py
- documentation/tests/test_map_model.py
Reverts code-dot-org/curriculumbuilder#212
> Revert "Use /docs instead of /documentation for links"

- curricula/templates/curricula/partials/admin_menu.html
We have this kind of secret way to generate the markdown for a Student Facing Lesson Plan (usually the first level of a lesson). It is just adding `/md` to the end of the lesson link. As we look to add more external editors to curriculum builder it would be nice to have an easy to access link for this so I added it to the admin menu on a lesson.
> Add link for SFLP Markdown in admin menu of lesson

- documentation/models.py
On curriculum builder we use the `get_published_url` for documentation in a couple of different places to determine the url we are sending people to for documentation. On of the them is the `/md` page for lesson plans which generates markdown for a student facing lesson plan which is used as the first level of most lessons. In addition, the blocks in lesson plans use this link. 
This changes those links to point to studio.code.org/docs instead of docs.code.org.
- [jira](https://codedotorg.atlassian.net/browse/LP-910)
> documentation links point to studio.code.org/docs instead of docs.code.org

- documentation/factories.py
- documentation/tests.py
- documentation/tests/test_documentation_models.py
Creates basic factories for models in Documentation (IDE, Block, Map).
Creates a test for functions that were changed by #219.
> Test for get_published_url for documentation models

- documentation/factories.py
- documentation/tests/test_documentation_admin.py
- documentation/tests/test_documentation_rendering.py
- standards/tests/test_standards_admin.py
Creates basic tests for admin abilities for documentation and standards. It only tests the add permissions and add pages (not change or delete). This is how we were testing for curricula and lesson.
- [jira](https://codedotorg.atlassian.net/browse/LP-1053)
> Test admin documentation standards

- documentation/templates/documentation/index.html
- documentation/tests/test_documentation_rendering.py
- documentation/urls.py
- documentation/views.py
Currently if you go to curriculum.code.org/documentation/ (also curriculum.code.org/docs) you get an error. This creates a page for the url so that if you end up there you can get to any of the IDE documentation or the concept maps. It is not a very pretty page but its better than an error.
- [jira](https://codedotorg.atlassian.net/browse/LP-1138)
Created a render test for the page.
> Create docs landing

- lessons/models.py
Users keep checking the google doc box on resources if its any google resource (spreadsheet, presentation, etc). It is ONLY for google docs. This adds help text to hopefully help people from checking the box at the wrong times.
> Add help text for google doc checkbox

- documentation/models.py
- documentation/tests/test_documentation_models.py
In an effort to consolidate the number of ways you can access documentation we are trying to move toward everything using /docs. curriculum.code.org currently uses /documentation because thats where the pages get published to on S3. Jackfrost is the thing we use to publish and the url it publishes to is determined by `jackfrost_url`.
This makes it so we will both publish to /documentation and /docs on S3. Once we publish everything and confirm its working at /docs then we can stop publishing to /documentation and just redirect /documentation to /docs.
- [jira](https://codedotorg.atlassian.net/browse/LP-1137)
I created a unit test for the `jackfrost_urls` method. I don't know that I can test that the action of publishing works locally.
> Make documentation also publish to /docs in addition to /documentation

- curricula/tests/test_curricula_rendering.py
- standards/tests/test_standards_rendering.py
- standards/views.py
[LP-1151](https://codedotorg.atlassian.net/browse/LP-1151) 
Teachers requested that the CSV download of standards include the description of the standard in the table. Turns out this is useful for the engineering work we're doing to show standards associations on the teacher dashboard too 🙂
BEFORE: 
CSV download includes columns for: curriculum, unit, lesson #, lesson name, standard framework, standard and cross curricular opportunity 
AFTER: 
CSV download includes columns for: curriculum, unit, lesson #, lesson name, standard framework, standard, category, description and cross curricular opportunity 
These updates were made in two places: the csv by unit and csv by curriculum methods. 
This PR also contains a small clean up from …
> Standards description and category in csv

- curricula/serializers.py
Follow up to #230 
Since the standards don't change once they're released, we're relying on CSV upload of the standards and don't need the description, name or category here. We're only using the CB metadata to establish the association between a standard and a stage/lesson. Framework  (Code Studio "organization" on the Standards model) and shortcode (Code Studio "organization_id" on the Standards model) will be sufficient to identify the standard in Code Studio.  
BEFORE:
AFTER:
> Limit standards metadata to needed fields

- curricula/models.py
- curricula/tests/test_curricula_rendering.py
- curriculumBuilder/settings.py
- i18n/management/commands/publish_i18n.py
We've wanted to add more language options to CB for a while. We haven't as the sync takes several hours every day. We believe that PDF generation is a major bottleneck, so this PR adds a way to limit the languages that generate translated PDFs. Languages that don't have translated PDFs will link to the English version.
This PR does add Hindi as a language option as I was testing these features out with Hindi. If we would prefer to keep adding a language separate, I can remove it.
> Limit pdf generation to a handful of languages

- curricula/admin.py
- curricula/models.py
- curricula/serializers.py
- curricula/templatetags/with_unit.py
- curricula/tests/test_curricula_rendering.py
- curricula/urls.py
- curricula/views.py
- lessons/models.py
- standards/tests/test_standards_rendering.py
Units in CurriculumBuilder align with Scripts in Code Studio. For example 'coursea-2019' references a Unit in Curriculum Builder and a Script in Code Studio. 
Lessons in CurriculumBuilder align with Stages in Code Studio, for example "Learn to Drag and Drop". 
While sending standards metadata from CurriculumBuilder to Code Studio, it was noted that the  `stage_name` attribute on CurriculumBuilder Units was erroneously labeled. ([see discussion on Code Studio PR](https://github.com/code-dot-org/code-dot-org/pull/32743#discussion_r367729866)).
This updates `stage_name` to `unit_name` and changes the Unit model to have a `unit_name` attribute that references the `stage_name` column in the database. The end result is that the standards metadata now accurately references `unit_name`.
> Change stage_name to unit_name to avoid further confusion

- curricula/views.py
Missed one in #242 which caused errors like: 
I renamed "stage" to "unit_name" and the page works now:
> stage -> unit_name follow up 

- curricula/models.py
The i18n pipeline has been crashing lately. This fix won't fix whatever exception is happening that is putting us into exception handling but will hopefully allow the i18n pipeline to proceed.
Solution from: https://stackoverflow.com/questions/28626984/unicodedecodeerror-when-logging-an-exception-in-python
- [spec]()
- [jira]()
> Fix unicode decode error in logging to prevent the i18n sync from crashing

- curriculumBuilder/settings.py
[FND-982](https://codedotorg.atlassian.net/browse/FND-982) lists 30 languages to add to the CB sync -- this PR covers the first 10 (Italian is listed on the ticket which is already synced).
I'm breaking this up so that we can monitor for any errors and fix them before enabling more languages.
I ran the `publish_i18n` step with PDF generation and without with 6 languages added.
Without PDF generation:
```Publishing 3 models in 6 languages finished in 0:21:07 (average of ~0:03:31 per language)```
With PDF generation on 4 languages:
```Publishing 3 models in 6 languages finished in 3:12:46 (average of ~0:32:07 per language)```
When I ran the sync with out PDF generation with all the newly added languages:
```Publishing 3 models in 15 languages finished in 0:45:49 (average of ~0:03:03 per …
```
> Add nine more languages to CB (none will have PDFs generated)

- curricula/templates/curricula/partials/hoc_lesson_front.html
Before:
After:
- [spec]()
- [jira]()
> Fix translation tag that was broken up onto multiple lines

- i18n/management/commands/publish_i18n.py
The i18n sync is still taking longer than we would like so let's disable pdf generation for a few days and see if this is a direction we want to take. If we do, I can create a better solution than this.
- [spec]()
- [jira]()
> Hack to turn off i18n pdf generation

- documentation/admin.py
When editing a Map in curriculum builder the View on Site button used to take you to codecurricula.com/concepts/.... with this change it will take you to codecurricula.com/docs/concepts/... which is the correct path. This already happens for IDEs and Block objects but not for Maps.
> Make view on site button for maps direct to correct link

- documentation/models.py
- documentation/templates/documentation/index.html
The links on studio.code.org/docs are not working because they need the trailing slash at the end to work. This makes that update so that we can generate that page to update it on S3.
> Fix the links on the docs landing page

- curricula/models.py
- curricula/views.py
Clean up logging on pdf generation path, to ensure all exceptions make it to application logs. Also, do some minor housekeeping
- move duplicated code between 'publish' and 'publish_pdf' into a seperate function
- add logging for parameters that determine if jackfrost can build, to help us debug issues with content generation due to parameters that could affect this function
> add logging to pdf generation path, cleanup code a bit

- lessons/static/css/commonlesson.css
In the guide styling on lesson plans the tiplink was still trying to slide to the left. This removes that old styling so tiplinks show in line in the guides like in the rest of the lesson plan.
> Remove old styling for tiplinks in guide

- curriculumBuilder/settings.py
- i18n/management/commands/publish_i18n.py
Also:
- Keep the languages we've always synced
- Turn PDF generation back on, but still only for a small list of languages
There's more discussion on [jira](https://codedotorg.atlassian.net/browse/FND-982)
> Only sync languages that are over 70% translated

- curricula/templates/curricula/partials/unit_calendar.html
On the Unit Overview page there is a pacing calendar. For really long titles the text was overflowing the space. Josh had already added short_title as a field that was used in the PL session header which is very similar to the calendar on the unit overview page.
This just takes advantage of that field and uses the short_title in the unit calendar if one is supplied.
In the screenshots below look at the difference on Lesson 13.
> Use short_title in unit calendar if one is supplied

- i18n/management/commands/publish_i18n.py
There are sometimes pdf publishing issues that are a result of content changes. While we should fix those, I don't think the whole pipeline should halt while we do.
- [spec]()
- [jira]()
> Catch and log pdf errors in publish_i18n without halting the whole pipeline

- curriculumBuilder/settings.py
Spanish is now synced at 99% so we can start syncing it:
This doesn't add Spanish to the list of languages we generate PDFs for.
- [spec]()
- [jira]()
> Sync es-es 

- requirements.txt
Auto deploy failed with error "Invalid input of type: 'CacheKey'. Convert to a bytes, string, int or float first.". Dave traced the issue down looking at: it looks like it has to do with the version of redis: https://github.com/jazzband/django-redis/issues/342. He found that https://github.com/jazzband/django-redis/blob/master/requirements.txt will take any latest version of redis. So even though we pin our version, they do not pin theirs. So pinning a redis version lesson that 3 should fix based on: https://stackoverflow.com/questions/53331405/django-compress-error-invalid-input-of-type-cachekey/53336728#53336728
> Pin version 2.10.6 of redis to fix auto deploy issue

- curricula/templates/curricula/partials/footer.html
ef493c6ba52c67960f1e4525cbfdd2b9b2a1d894 introduced a regression, where the
creative commons banner broke on all pages that are not lesson pages. This PR
fixes this regression
- [jira](https://codedotorg.atlassian.net/browse/LP-1283)
> Fix creative commons banner for non-lesson pages

- curricula/templates/curricula/partials/lesson_front.html
- curricula/templates/curricula/partials/vocab_list.html
Mike reported that the CSP/CSD definition was showing up on CSF courses. I'm not sure when we stopped using the simple definition but I put this temporary fix in until we move vocab over to Code Studio and make it per course.
| Before | After |
| -- | -- |
| ![Screen Shot 2020-04-30 at 4 14 01 PM](https://user-images.githubusercontent.com/208083/80754766-9cc90480-8afd-11ea-9bd7-1bd9c1b954be.png) | ![Screen Shot 2020-04-30 at 4 13 14 PM](https://user-images.githubusercontent.com/208083/80754720-815df980-8afd-11ea-922f-b3b084844522.png) |
| Before | After |
| -- | -- |
| ![Screen Shot 2020-04-30 at 4 10 06 PM](https://user-images.githubusercontent.com/208083/80754658-67bcb200-8afd-11ea-9286-c88c661eec21.png) | ![Screen Shot 2020-04-30 at 4 10 13 …
> Make sure we use the simpleDef for CSF courses

- curriculumBuilder/settings.py
- i18n/middleware.py
- i18n/tests/test_url_resolver.py
Django documentation a lot of this work was based on is [here](https://docs.djangoproject.com/en/1.8/topics/i18n/translation/#how-django-discovers-language-preference)
In the past, we've attempted to sync Polish but it caused problems because `/pl-sandbox/` resolved to be in Polish. It turns out that Django automatically uses the "base language" if it can't find the locale, so Django thought `sandbox` was a locale. This PR overrides that logic to only use the URL locale if it is an exact match to one we have enabled.
I rearranged the order of the middleware to be in line with the above documentation and because it wasn't working before I moved the `StrictLocaleMiddleware` to be after `SessionMiddleware`.
- [jira](https://codedotorg.atlassian.net/browse/FND-997)
- Added a unit test. 
- …
> Override locale middleware

- i18n/management/commands/i18n_sync_down.py
Some [bad translations](https://crowdin.com/translate/curriculumbuilder/22478/en-it#2066606) in the curriculumbuilder project broke the sync out a while back. Unfortunately, the only thing logged was "[ERROR: I18n Sync encountered a problem and did not complete](https://codedotorg.slack.com/archives/C0SUN2VT5/p1586416862303900)". With this change, we will also log the content of the error itself to make future debugging easier.
> log errors in the i18n sync out

- documentation/templates/documentation/partials/block.html
See https://codedotorg.atlassian.net/browse/LP-1424
From zendesk - A user reported that w3schools pages were not showing up in iframes on our documentation site, rendering an empty white box where a page used to appear.
The error outlined by the user is due to w3schools setting the X-Frame-Options header in HTTP responses to requests to their site to DENY. In english, this means that they are explicitly forbidding browsers from showing content from their site inside of iframes, as we are doing. Websites often do this in order to stop clickjacking attacks - sites posing as impostors of their site using iframes, for malicious purposes. If interested you can read more about this here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options and here: …
> Hide iframe for w3schools documentation

- documentation/migrations/0021_example_example_app_display_type.py
- documentation/migrations/0022_auto_20200512_0310.py
- documentation/migrations/0023_auto_20200514_0024.py
- documentation/models.py
- documentation/templates/documentation/partials/block.html
- static/cdo/css/applab-docs.css
This PR is the curriculumbuilder side of changes that allow us to embed projects directly in curriculumbuilder documentation. These changes add a new field,  'App Display Type', which specifies weather an app link in a documentation example should resolve to the new view (app with code from the project) or the old view (code is specified in curriculumbuilder, app is rendered from project). 
New view on docs page:
- [jira](https://codedotorg.atlassian.net/browse/LP-790)
New field in curriculum builder admin page:
> Embed app and code

- curricula/models.py
- standards/templates/standards/curriculum_nogrid.html
[LP-1250](https://codedotorg.atlassian.net/browse/LP-1250) partial 
CSF overview standards pages will now how explanatory text introducing standards and cross-curricular opportunities: 
Same for specific CSF courses: 
Non-CSF course standards pages on curriculum.code.org will remain unchanged:
> Explanatory text and links for CSF standards and cross-curricular opportunities

- curriculumBuilder/settings.py
disable the mdlightbox plugin, which automatically wraps all images on curriculumbuilder in a [lightbox](https://en.wikipedia.org/wiki/Lightbox_(JavaScript)). there are two reasons for this:
1. As part of moving block and concept docs from Curriculum Builder to Level Builder, we need to eliminate html syntax from markdown. to accomplish that, we'd like to be able to use markdown to create images which are also links. The current lightbox plugin prevents that, because it overwrites the link target with a link to 
2. The current behavior is broken anyway (see screenshots). clicking the image navigates to the image, instead of opening a lightbox.
^ you can see at bottom left (and in the html) that the image is a simple link to itself
> disable mdlightbox plugin

- static/cdo/css/applab-docs.css
Previously, the iframe's height was too low. Examples would get the app border
cut off, causing a worse user experience (though it was still functional). This
change allows the app border to render
Before:
After:
> Increase height of gamelab-exemplar

- curricula/templates/curricula/partials/unit_pills.html
This is to ensure that Unit PDFs on codecurricula.com always show if they have
been published. Previously, the django app would re-generate Unit PDFs every
time they were requested, which could cause timeout errors that confuse site
visitors.
This change was made to address bug reports we got where folks requesting PDFs on codecurricula.com via these links would sometimes get error pages. They will now never get error pages if the PDFs for these pages have already been published - pdf publishing functionality has remained unchanged.
- [jira](https://codedotorg.atlassian.net/browse/LP-1495)
Tested by verifying links work as expected manually.
> Always Link Unit PDFs to curriculum.code.org

- curriculumBuilder/tests/test_tips.py
Mostly to capture the strange behavior for "guide" tips noticed here https://github.com/code-dot-org/remark-plugins/pull/25#discussion_r450452362
> add a simple test for rendering the 'tips' plugin

- curriculumBuilder/resourcelinks.py
- curriculumBuilder/tests/test_resourcelinks.py
Specifically to support translations which use unicode; currently, attempts to render translated resourcelinks that include accented characters fail with a UnicodeDecodeError.
Before | After
--- | ---
- [jira](https://codedotorg.atlassian.net/browse/FND-1210)
Also add a basic unit test.
> Allow use of unicode in resourcelinks

- lessons/admin.py
- lessons/migrations/0048_lesson_code_studio_url.py
- lessons/models.py
Finishes https://codedotorg.atlassian.net/browse/PLAT-240 . See https://github.com/code-dot-org/curriculumbuilder/pull/297 for migration PR.
Manually verified the following:
How the field appears on the lesson admin page:
new link viewable on hover over the View on Code Studio link:
Also, no change to behavior on lessons with blank code_studio_url field.
Since we don't expect this code to live long, I haven't added any unit tests.
> add code studio url override to lesson model

- curricula/models.py
- curricula/templates/curricula/partials/curriculum_pills.html
The new CSP course does not have linked blocks or vocab in lesson plans. The unit overview page already hides the tabs for the all blocks and all vocab page if there are no blocks or no vocab. This hides the tabs on the curriculum overview page if there are no blocks or no vocab.
I checked that csp-20 now hides the correct tabs and that csd-20 does not hide those tabs because it does have vocab and blocks.
> Hide blocks and vocab tabs if there are no blocks or vocab

- i18n/management/commands/publish_i18n.py
Specifically, parallelize the act of iterating through each model object. Testing on my local machine confirms that this speeds up the publish step proportional to the number of processor cores used. It looks like heroku dynos have between 2 and 4 cores, so we should expect a comparable speedup.
Once we've deployed this and looked into the results, I'd like to also explore the effects of allocating more resources to the dyno that runs the sync.
We could also look into parallelizing this at the language level rather than at the object level, but local testing doesn't indicate that that results in any significant improvement over this approach.
- [jira](https://codedotorg.atlassian.net/browse/FND-625)
Manually tested.
> Parallelize "publish" operations in I18n sync

- README.md
When installing python requirements (by `pip install -r requirements.txt`), `psycopg2` could fail to build if it cannot find `openssl` library. Add instruction to fix this error.
> Add instruction to fix psycopg2 install error

- curriculumBuilder/tests/test_tips.py
[FND-1219](https://codedotorg.atlassian.net/browse/FND-1219): The python-markdown renderer has some strange behaviors, and we want to document two of them using unit-tests.
1. If there is a blank line between two paragraphs, they will be wrapped in separate divs.
2. If there is a blank line between a admonition title and a paragraph, it will render an empty div.
- [python-markdown](https://python-markdown.github.io/)
- [Admonition extension for python-markdown](https://python-markdown.github.io/extensions/admonition/)
- [babelmark](https://babelmark.github.io/) to check markdown-to-html output of different rendering programs.
In curriculumbuilder repo root:
```bash
pipenv shell
./manage.py test curriculumBuilder    # run all tests in curriculumBuilder folder
./manage.py test    # run all …
```
> Add tests for Tips renderer

- curricula/templates/curricula/partials/lesson_front.html
- curriculumBuilder/local_settings.py.example
we need to hard-code the Common Sense Education logo above the overview for common sense lessons. we already have a sort of flag denoting those lessons, which is that they use a unique creative commons image. so rather than adding an additional flag to indicate the need for this hard-coded logo (which would need to stay in sync with the image choice), it was decided to use the image choice to determine the need for this logo.
as soon as this PR is deployed, i will manually remove the image from the markdown in all the common sense lessons.
- [jira](https://codedotorg.atlassian.net/browse/LP-1504)
> Hardcode Common Sense Logo

- i18n/management/commands/i18n_sync_down.py
- i18n/management/commands/publish_i18n.py
- i18n/management/crowdin.py
- i18n/management/utils.py
- i18n/tests/test_crowdin.py
Inspired by [the similar changes](https://github.com/code-dot-org/code-dot-org/pull/34846) we recently made to the regular code.org repo.
This PR adds a new class which contains all the logic for interacting with Crowdin. It includes support for tracking etags for each file in each language and persists that data to S3 so it can be used by the next sync. It also generates a list of files changed by the most recent sync in each language (this file is not persisted); that list of changes is then used by the publish to entirely skip languages for which there were no changes.
We're unfortunately not able to skip publishing at a finer-grained level than "skip the entire language" given our current organization of data. Hopefully the fact that we have relatively frequent syncs and relatively …
> Allow the i18n sync process to detect changes, and skip publishing accordingly

- i18n/management/crowdin.py
- i18n/tests/test_crowdin.py
Fix for the new sync approach defined in https://github.com/code-dot-org/curriculumbuilder/pull/305 to use the S3-compatible I18nFileWrapper for etag detection; as currently implemented, it won't find the etags file so we'll do a full sync each time.
> use I18nFileWrapper for loading etags

- i18n/management/crowdin.py
- i18n/tests/test_crowdin.py
The whole storage abstraction we have going on here is significantly more confusing than it needs to be.
So the way it works is the "absolute path" really only works for local filesystems; when we're using a virtual filesystem like we do in production, we need to use the relative path and also make sure to use the Storage-specific `open` operator rather than the OS-provided one.
We also need to be careful with how we handle creation of directories, since the whole concept of directories is itself filesystem specific and doesn't apply to S3.
> more attempts to fix the S3 interaction for the i18n sync

- i18n/management/commands/publish_i18n.py
Also make it be a bit more explicit about exactly which languages it's publishing.
When we added the ability for the sync to skip publishing languages without translation changes in https://github.com/code-dot-org/curriculumbuilder/pull/305, we undid the parallelization stuff to get it to work. This PR reintroduces parallelization! We also update the time tracking and time reporting stuff to be a bit more explicit about exactly what's going on.
> Re-parallelize the publish operation

- curriculumBuilder/settings.py
So that we can access this list of languages both from the CurriculumBuilder project (where we need it for the i18n sync) and from the Code.org project (where we need it for various display/linking operations)
Tested manually
> Use external source of truth for LANGUAGES setting

- i18n/management/utils.py
- i18n/middleware.py
follow-up from https://github.com/code-dot-org/curriculumbuilder/pull/313
> log to slack when the i18n sync thinks we're operating on an incomplete list of languages

- requirements-dev.txt
I was setting up the curriculum builder for the first time and the unit tests failed because of a missing dependency.
`./manage.py test`
> Addding the 'mock' dependency for unit tests

- curricula/serializers.py
Reimplements #315 using serializers. This seems a little less error-prone, for example switching over to serializers gave me a friendly error when a field I asked for did not exist. 
I decided to make a separate set of serializers for now, because (1) I want to be able to keep junk we don't need out of this json, and (2) I don't want to clutter up the json we already use for pulling stage details at https://www.codecurricula.com/metadata/coursea-2020.json , and (3) this gives extra insurance against somehow breaking the process of pulling stage details.
Current usage:
```
(cb) Dave-MBP:~/src/cb (serialize-activities)$ ./manage.py shell_plus
In [1]: from curricula.serializers import *
In [2]: import json
In [3]: unit = Unit.objects.get(unit_name='coursea-2020')
In [4]: data = …
```
> serialize Unit, Chapter, Lesson and Activity using serializers

- curricula/serializers.py
Follow-on to https://github.com/code-dot-org/curriculumbuilder/pull/319 . These fields are needed to match curriculum builder lessons to code studio lessons.
> export stage_name and code_studio_url fields for lessons

- curricula/models.py
Finishes code changes for [PLAT-500](https://codedotorg.atlassian.net/browse/PLAT-500). After this is deployed, I'll need to go publish every unit in CSF / CSD / CSP 2020 before closing out the work item. This work is needed in order to be able to import cb data into an adhoc or levelbuilder without slowing down codecurricula.com for curriculum writers.
This PR copies the approach for publishing standards in https://github.com/code-dot-org/curriculumbuilder/pull/256.
I was not able to test publishing locally, so I performed some hand-wavy verification steps as best I could.
From http://localhost:8000/csf-20/coursea/ I clicked Publish in the admin menu. The debug output looked promising:
```
127.0.0.1 - - [11/Nov/2020 20:40:13] "GET /publish/?pk=5103&type=Unit&lessons=false HTTP/1.1" 200 - …
```
> include unit export json when publishing a unit

- curricula/serializers.py
Unfortunately, the image path is stored for each lesson so I had to reverse the logic [here](https://github.com/code-dot-org/curriculumbuilder/blob/a2b92677069aa5deae0726ead47fa70e2399e50a/lessons/models.py#L353) to get the actual license name. I did a quick spot check and these strings match the ones we expect in code studio.
- [spec]()
- [jira]()
> Export Creative Commons license to import into Code Studio

- curricula/serializers.py
Starts [PLAT-517](https://codedotorg.atlassian.net/browse/PLAT-517). Adds resources to each exported lesson. The list of exported fields roughly covers all of the columns and properties on the Resource model, except for internal rails ids.
new fields appear to be populated:
> include resources in lesson export

- README.md
Adding a Readme warning for users to avoid using Heroku CLI commands that may unintentionally manipulate the production database.
- [spec]()
- [jira]()
> adding a warning for Heroku CLI command

- i18n/management/crowdin.py
The i18n-down-sync failed on Curriculum builder because it failed to find the translations for `uz-uz` which is the new Uzbek language. It failed to find the translation on Crowdin because Crowdin uses the language code`uz`. This PR adds the mapping of `uz-uz` to `uz`.
```
20.         Crowdin().download_translations()
File "/app/i18n/management/crowdin.py" in download_translations
197.                             response.status_code, filepath, language_code
Exception Type: Exception
Exception Value: Cannot handle response code 404 for file "Curriculum.json" in language "uz-uz"
Request data not supplied
```
* ran `./manage.py i18n_sync_down` on my laptop
> Adding the Crowdin language code mapping for Uzbek

- curricula/templates/curricula/partials/footer.html
- curricula/templates/curricula/partials/language_select.html
- curriculumBuilder/settings.py
- i18n/context_processors.py
- i18n/management/utils.py
- i18n/tests/test_context_processors.py
Looks like this:
Works like you'd expect.
Right now, it displays all languages in English. To improve this experience, we should go into DynamoDB and set the language names as defined in there to display each language name in its own language (as we do for the code.org language select dropdown). Out of an abundance of caution, I'm going to hold off on making that data change (and merging this PR) until after Hour of Code.
Added a basic unit test. Could theoretically add a UI test of some kind, but that seems unnecessary. Open to suggestions if y'all feel otherwise.
> Add a basic "language select" dropdown

- i18n/management/commands/i18n_message_file_sync.py
- i18n/management/crowdin.py
- i18n/utils.py
As discussed offline, we're adding a script that downloads `django.po`  files from Crowdin and compiles them into their respective `django.mo` files. The script is very similar to the [`download_translations`](https://github.com/code-dot-org/curriculumbuilder/blob/master/i18n/management/crowdin.py#L136) function in crowdin.py.
Functionality was tested by: 
1. removing all translations from my local file system, running the `i18n_message_file_sync` command, 
2. verifying that the `django.po` and `.mo` files have been successfully downloaded to the `i18n/static/translations` directory, and
3. verifying that the translated UI element strings show correctly on the local server
Before:
After:
- [spec]()
- [jira]()
> adding python script to locally download django.po and .mo files in CB

- requirements.txt
This was the first step for me in fixing a long list of build problems on OS X. Here is everything that i did to get my system working:
1. at some point, brew made me upgrade to openssl@1.1.
2. `pip install -r requirements.txt` broke with:
```
django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 module: dlopen(/Users/dsb/.virtualenvs/cb/lib/python2.7/site-packages/psycopg2/_psycopg.so, 2): Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
```
I tried installing an older version of openssl, but that didn't work. 
3. I upgraded psycopg2 to the latest version, as shown in this PR. 
4. `pip install -r requirements.txt` now succeeds
5. `debug=true python manage.py runserver_plus` fails with:
```
OperationalError: could not connect to server: No such file or …
```
> upgrade to psycopg2 version 2.8.6

- README.md
Last sprint, I wrote setup instructions for the CB i18n sync. In this PR I'm linking those instructions from the main README to make them more accessible to people trying to set up the repo
- [spec]()
- [jira]()
> adding a link to i18n setup instructions from the README

- standards/models.py
We noticed that Categories which don't directly contain any Standards are not recognized as translatable. This change makes it so if there are any child Categories which contain a Standard, then the Parent Category will be marked for translation.
Example of bug:
Note how **Engineering in the Sciences** is not translatable, but the child Category and Standard are.
- [jira](https://codedotorg.atlassian.net/browse/FND-1239)
Ran `./managepy gather_i18n_strings` and verified that "Engineering in the Sciences" and a few other Categories are now available in `i18n/static/source/Category.json`. This file contains the Categories which are translatable.
> Parent Categories are translatable

- curricula/templates/curricula/partials/hoc_lesson_front.html
- curricula/templates/curricula/partials/pl_lesson_front.html
Updates the HOC lesson plans on Curriculum Builder to use `translated_keywords` instead of `keywords` so that the translated value of the keyword is displayed to the teacher. Examples for keywords: "Grades 3-5", "Grades6-8", etc.
Note that **Grades 3-5** is now outlined which indicates its a translatable field by Crowdin
- [JIRA](https://codedotorg.atlassian.net/browse/FND-1405)
> Using the translated string for keywowrds such as Grade levels

- curricula/serializers.py
Continues on [PLAT-751](https://codedotorg.atlassian.net/browse/PLAT-751). For more background, see [Lesson Standards design doc](https://docs.google.com/document/d/1zvdv7y8VuRz8KqT1rzqeJAmvirCvUr1jS8OWy0p9FHk/edit)
There is an existing way to export lesson-standards relationships, but it has to be run manually for each script via web UI. This PR builds on the existing lesson/unit export functionality instead, which seems better because the existing import_unit_details.rb script is already set up to import this format and also serialize it to script json.
> include standards in lesson export

- curricula/templates/curricula/hoc_lesson.html
- curricula/templates/curricula/partials/lesson.html
- curricula/templates/curricula/partials/pl_lesson.html
- curricula/templates/curricula/pl_lesson.html
- standards/templates/standards/curriculum-supertable.html
- standards/templates/standards/curriculum-tabulator.html
- standards/templates/standards/curriculum.html
- standards/templates/standards/curriculum_nogrid.html
- standards/templates/standards/framework.html
- standards/templates/standards/index.html
- standards/templates/standards/standard.html
- templates/pages/lesson.html
Some shared header text in the lesson plans ("Standards Alignment", "Cross-curricular Opportunities", and more) have translations available, but are not using the `trans` tag to correctly display the translations. This PR adds those tags so that the translated strings display instead of English.
[jira](https://codedotorg.atlassian.net/secure/RapidBoard.jspa?rapidView=28&modal=detail&selectedIssue=FND-1462)
> adding trans tags to make UI headers and text translatable

- curricula/templates/curricula/unit.html
- lessons/models.py
Prior to this change, the translated_keywords function only returned keywords if the language was non-English, causing English pages to show no keywords on some pages. This PR adds a fallback to return English keywords if the language is English. 
Additionally, this PR makes "Students Links" and "Teacher Links" translatable in code paths where it was previously missed.
- [spec]()
- [jira](https://codedotorg.atlassian.net/secure/RapidBoard.jspa?rapidView=28&modal=detail&selectedIssue=FND-1466)
Manually tested on localhost
> Add translated keyword strings

- i18n/management/commands/i18n_sync_down.py
- i18n/management/commands/log_i18n_failure.py
- templates/slack/message.slack
Updates the CurriculumBuilder i18n sync to ping @foundations-team when the i18n sync fails. This will be useful because we often don't notice when this system is broken.
* [JIRA](https://codedotorg.atlassian.net/browse/FND-1401)
Manually tested and successfully notified the slack group.
> Fnd 1401 add notification on i18n failure

- Procfile
- app.json
- config/nginx.conf.erb
Turns out, we didn't have to do much at all to get Heroku 18 to work!
- Heroku has deprecated `bin/start-pgbouncer-stunnel`in favor of `bin/start-pgbouncer`. In fact, the former is now [just an alias to the latter](https://github.com/heroku/heroku-buildpack-pgbouncer/blob/b229604a206c4d350405496f97e2175e8b7caf70/bin/start-pgbouncer-stunnel#L3-L6) so we can safely switch this without needing to do any follow-up work
- We were formerly on a custom branch of the nginx buildpack, which has not been updated to support modern infrastructure. Switch back to the mainline branch instead. It's not at all clear to me why we were on that custom branch, but I haven't been able to find any issues with the mainline branch through manual testing.
- The nginx directive `content_by_lua_block` requires an …
> Upgrade stack to Heroku 18

- curricula/tests/test_curricula_rendering.py
- lessons/models.py
The URL update we made on Code Studio( https://github.com/code-dot-org/code-dot-org/pull/38802) from /stage to /lessons broke the code studio pull through (https://codedotorg.slack.com/archives/CNZP84FJ5/p1619128208169200) . This updates that path as well as a couple other things that were pointing to /stage or /puzzle.
> update urls to use lessons and levels instead of stage and puzzle

- app.json
- i18n/SETUP.md
- i18n/heroku_crowdin.sh
- i18n/management/commands/i18n_sync_up.py
Reverts code-dot-org/curriculumbuilder#359
All the great effects of that PR were conditional on us adding the `heroku/jvm` buildpack so we could get hack-free Java functionality. Unfortunately, it turns out heroku has a hard limit on slug size, which includes the size of all included buildpacks, and adding this buildpack put us over the limit. I poked around a bit looking for other things we could cut to reduce size, but unfortunately couldn't find anything. So it's back to the hack. :(
> Revert "Java updates for Heroku 18"

- curricula/models.py
publishing broken after all the units in codecurricla.com/plcsd-21 were hidden. publishing broke because publishing plcsd-21 depends on loading /plcsd-21/standards, which broke because of https://github.com/code-dot-org/curriculumbuilder/blob/09018bd2211d68ac8eb9b850899d0fad9b257426/curricula/models.py#L265-L266
The solution is to safely check whether any units have cross curricular info, even if they are all hidden.
I was able to repro the original problem locally. after the fix, I verified the following locally:
* I can now load http://localhost:8000/plcsd-21/standards
* I can still load http://localhost:8000/plcsd-20/standards, and it looks the same as codecurricula.com/plcsd-20/standards
> safely check whether any units have cross curricular info

- Aptfile
- i18n/heroku_crowdin.sh
Okay, this one was an adventure. So, when we upgraded our heroku stack to Heroku-18, one of the changes was that the version of Java installed on our dynos changed from 8 to 11. This broke the hack we were using to get the Crowdin CLI to execute, and (after an unsuccessful detour trying to replace the hack with a real implementation) so we had to manually update the hack to java 11. Unfortunately, after doing so we started getting this error:
```
Exception in thread "main" java.lang.ExceptionInInitializerError
at java.base/javax.crypto.Cipher.getInstance(Cipher.java:540)
at java.base/sun.security.ssl.JsseJce.getCipher(JsseJce.java:185)
at java.base/sun.security.ssl.SSLCipher.isTransformationAvailable(SSLCipher.java:483)
at java.base/sun.security.ssl.SSLCipher.<init>(SSLCipher.java:472)
at …
```
> lock to java 8

- documentation/templates/documentation/partials/block.html
Dan pointed out in [slack](https://codedotorg.slack.com/archives/CNZP84FJ5/p1629488524032000) that the backlinks like `buzzer` on pages like https://studio.code.org/docs/applab/buzzer.frequency/ are broken.
> add /docs prefix to block parent backlink url

- curricula/urls.py
- curricula/views.py
the existing process for importing cb content into code studio requires a unit to exist on CB which is tagged with the code studio unit name. when importing CB data for the 2021 curriculum, this served as a safeguard to help make sure we always imported the correct CB unit into the corresponding code studio unit.
in order to import hoc lesson plans into code studio, we need to be a bit more flexible. code studio units like studio.code.org/s/dance do not have a corresponding units on CB. rather, HOC scripts each contain individual lessons which have lesson plans on CB at urls like https://curriculum.code.org/hoc/plugged/8/ . the full mapping of HOC scripts to CB lessons is here: https://docs.google.com/spreadsheets/d/1inzBUu4tlPh82JDiBIMCKVHacaMI-Hutex2e9inOJ4E/edit#gid=0
Adds a new path …
> add a new path to export hoc lesson details to code studio

- i18n/management/commands/publish_i18n.py
We only publish changes for a language if there have been changes downloaded. There is some logging code which divide by the number of languages with changes. If no languages have changed, then the logging code ends up dividing by 0. The fix is to skip the whole I18n publish step if we don't have any changes since it won't be publishing anything.
You can see the line where the divide-by-zero happens [here](https://github.com/code-dot-org/curriculumbuilder/blob/5422d02973ece252a43a03931acc808494919ae0/i18n/management/commands/publish_i18n.py#L129). The stacktrace for the exception can be seen below.
- [JIRA](https://codedotorg.atlassian.net/browse/FND-1735)
* Setting up test environment now, will verify the fix before merging.
Here is the error logged in the #curriculumbuilder slack …
> Fixing divide-by-zero error in publish_i18n

- documentation/serializers.py
- documentation/urls.py
- documentation/views.py
Adds a new endpoint to expose the concept maps as formatted json. Provides the list of children, too, to make it easier to recursively discover all concept maps from the import side.
modelled after these previous PRs:
https://github.com/code-dot-org/curriculumbuilder/pull/318
https://github.com/code-dot-org/curriculumbuilder/pull/319
sample data:
> add endpoint for json formatted concept maps

- documentation/serializers.py
- requirements.txt
Adds the order field to the list of fields exported for concept maps.
Also updates the git:// requirements to be https:// to conform with github security changes: https://github.blog/2021-09-01-improving-git-protocol-security-github/
- [spec]()
- [jira]()
Tested manually on local curriculumbuilder with import script
> Concept maps export order field
