.travis.yml
lessons/migrations/0001_squashed_0003_auto_20150624_1139.py
requirements.txt

Lots of iterative commits here, but the ultimate work done boils down to just three changes:
1. Use `manage.py migrate` instead of `manage.py syncdb`
2. Configure correct version of Postgres
3. Squash some early commits that otherwise caused problems

Fix travis

---

lessons/admin.py

Adding for ryan to track resources needing translation

Add export resource to lesson resource

---

curriculumBuilder/vocablinks.py

Vocablinks can now look like `[v vocabWord][overrideWord]` as well as like the original `[v vocabWord]` syntax. In the new form, the rendered tag would still use the original `vocabWord` and definition for the hover text, but use `overrideWord` for the hoverable element.
This will allow us to do things like this for i18n

extend vocablink to support optional override

---

curricula/models.py
i18n/management/commands/gather_i18n_strings.py
i18n/models.py
lessons/models.py

Follow-up work: make Activity names unique per lesson and give them a string-based `i18n_key`

Make Activities and Chapters internationalizable

---

i18n/models.py
lessons/models.py

Also optimize string gathering a bit by using `select_related` and only calling `i18n_key` once so we don't waste a bunch of time with fk lookups

 give Activities a string-based i18n key 

---

curricula/templates/curricula/partials/code_studio.html
curricula/templatetags/level_link.py

Hotfix for links to lesson extras in code studio pullthrough

Extras fix

---

curricula/templates/curricula/codestudiolesson.html
curricula/templates/curricula/partials/lesson.html
curricula/templatetags/with_unit.py
documentation/templates/documentation/map.html

replace placeholder with unit name when displaying activity.content for code studio lessons

---

curricula/templates/curricula/partials/lesson_front.html
lessons/admin.py
lessons/migrations/0042_lesson_assessment.py
lessons/models.py

Adds an area to list the assessments for a lesson on the front page of the lesson.

Lesson Front Page: Add Assessment Opportunity Area

---

curricula/templates/curricula/partials/code_studio.html
lessons/static/css/commonlesson.css
static/css/common.css

If a level in CSD 2019 is marked as an assessment it will get this indicator showing its an assessment level. Also see below for what it looks like when you expand one of the levels.
If a level in CSD 2019 has a rubric it will be pulled through into the Code Studio Levels Overview.

Code Studio Lesson Pull Through: Mini Rubric and Assessment Indicator

---

curriculumBuilder/settings.py
i18n/context_processors.py
templates/basecurriculum.html

See [the crowdin documentation](https://support.crowdin.com/in-context-localization/) for more info

Enable in-context translation

---

.travis.yml
standards/tests.py

(including new unicode support)

add a basic test for Standards CSV functionality

---

i18n/management/commands/publish_i18n.py

Some prereq work to [speeding up the publish
operation](https://codedotorg.atlassian.net/browse/FND-17); I'd like to
start logging how long the operation takes on average currently, so we
can both identify which models take the longest and track improvements.

Add elapsed time logging to publish operation

---

curricula/templates/curricula/lesson_title.html

Fix unit resources pdf to correctly render unicode characters.

---

lessons/models.py

[Jira](https://codedotorg.atlassian.net/browse/FND-240)

make Objectives translatable

---

standards/models.py

[Jira](https://codedotorg.atlassian.net/browse/FND-264)

make the various standards models translatable

---

lessons/models.py

[Jira](https://codedotorg.atlassian.net/browse/FND-258)

Translate activity times

---

curricula/templates/curricula/partials/code_studio.html

Mini Rubric: Change title for mini rubric pull through

---

curricula/templates/curricula/partials/code_studio.html

Update rubric performance headers to match code studio update

---

curricula/templates/curricula/partials/curriculum_pills.html
curricula/templates/curricula/partials/lesson_pills.html
curricula/templates/curricula/partials/unit_pills.html

https://codedotorg.atlassian.net/browse/FND-233
https://codedotorg.atlassian.net/browse/FND-234
https://codedotorg.atlassian.net/browse/FND-235

Add template translations for lesson details

---

curricula/templates/curricula/partials/curriculum_pills.html

Sorry I missed this in code review :/

Load i18n on template

---

curricula/migrations/0030_auto_20190508_1556.py
curricula/models.py
standards/templates/standards/curriculum_nogrid.html

To better communicate how each course approaches assessment in general, and in particular in the context of aligned standards frameworks, I'm adding an "assessment_commentary" field to both the curriculum and unit models. This field gets rendered at the top of the curriculum and unit standards overview pages.

Assessment Field

---

curricula/templates/curricula/partials/lesson.html
curricula/templates/curricula/partials/lesson_front.html

I'm skipping the "Anchor Standard", "Standards Alignment" and "Cross-curricular Opportunities" headers because this shouldn't apply for non-US schools.

Translate lesson UI text strings

---

README.md

Updates README with information on the deploy and updating your local database

Updating the README: How deploy works

---

curricula/templates/curricula/partials/footer.html
curricula/templates/curricula/partials/lesson.html
curricula/templates/curricula/partials/pl_lesson.html
templates/basecurriculum.html
templates/basestandards.html
templates/cdo_base.html
templates/cdo_base.html.orig

I haven't updated the Creative Commons image yet, to point to a locale-specific image. Planning to do that in a future PR!

Extract footer.html partial and make it translatable

---

curricula/serializers.py
i18n/models.py
lessons/models.py

Reverts mrjoshida/curriculumbuilder#118
https://codedotorg.slack.com/archives/C0T0UQH0R/p1560277575025200

Revert "Keywords i18n serializer"

---

lessons/models.py

Following the pattern in https://docs.djangoproject.com/en/1.8/topics/i18n/translation/.

Translate the download link for resources

---

curricula/templates/curricula/codestudiolesson.html
curricula/templates/curricula/partials/curriculum_pills.html

Last of the Curriculum Builder UI strings for CSF.

Translate UI strings for "Standards Alignment"

---

curricula/templates/curricula/partials/lesson_front.html
curricula/templates/curricula/unit.html
i18n/management/utils.py
lessons/models.py

Better approach for PR https://github.com/mrjoshida/curriculumbuilder/pull/118.
Sample Keywords.json entries:
```js
"collector": {
"title": "Collector"
}, 
"common-sense-education": {
"title": "Common Sense Education"
}, 
"community-session": {
"title": "community session"
}, 
"computer-lab": {
"title": "computer lab"
}, 
```

Keywords proxy

---

curricula/templates/curricula/chapter.html
curricula/templates/curricula/codestudiolesson.html
curricula/templates/curricula/curriculum.html
curricula/templates/curricula/partials/lesson_front.html
curricula/templates/curricula/partials/resource_list.html
curricula/templates/curricula/partials/vocab_list.html
curricula/templates/curricula/unit.html
standards/templates/standards/curriculum_nogrid.html

Hopefully the last few UI strings to add to the `django.po` file!

Translate miscellaneous remaining strings

---

curriculumBuilder/details.py
curriculumBuilder/testDetails.py

See https://github.com/code-dot-org/code-dot-org/pull/28975 for more info

add a plugin for parsing the new Details syntax in level instructions

---

standards/models.py

Fixes AP and ETS standards on this view:

Translate all standards, not just cross-curricular opportunities

---

curricula/tests.py
curriculumBuilder/settings.py

https://codedotorg.atlassian.net/browse/FND-291

Only allow certain domains to be used as the src attribute for iframes

---

curricula/models.py

Follow-on to https://github.com/code-dot-org/curriculumbuilder/pull/175 , which I merged into the wrong branch. this just merges that PR into master.

Actually limit what partners can select in lesson dropdowns

---

curricula/admin.py
lessons/admin.py
lessons/tests.py
lessons/tests/test_lessons_admin.py

Filter unit & curriculum fieldsets

---

curriculumBuilder/local_settings.py.example

comment out STATIC vars in local settings example

---

documentation/templatetags/documentation_extras.py
documentation/tests/test_map_model.py

missed docs.code.org and codecurricula.com in https://github.com/code-dot-org/curriculumbuilder/pull/205/

More docs url

---

documentation/templatetags/documentation_extras.py
documentation/tests/test_map_model.py

Reverts code-dot-org/curriculumbuilder#206

Revert "More docs url"

---

curricula/urls.py
documentation/templatetags/documentation_extras.py
documentation/tests/test_map_model.py

Reverts code-dot-org/curriculumbuilder#213

Revert "Add www.codecurricula.com back"

---

documentation/templatetags/documentation_extras.py

Reverts code-dot-org/curriculumbuilder#211

Revert "Add testserver as a host"

---

curricula/templates/curricula/hoc_lesson.html
curricula/templates/curricula/partials/hoc_lesson_front.html

[jira](https://codedotorg.atlassian.net/browse/FND-926)

Make the HOC lesson pages more translateable

---

documentation/tests/test_documentation_rendering.py

Test that the blocks introduced page for a course and a lesson plan with blocks introduced render correctly.
Future work: Figure out how to test the IDE documentation and the Concepts Maps.
- [jira](https://codedotorg.atlassian.net/browse/LP-1052)

Create tests for course blocks page and lesson plan blocks

---

documentation/factories.py
documentation/tests/test_documentation_rendering.py

Test that the IDE blocks page and the concept maps pages render. 
- [jira](https://codedotorg.atlassian.net/browse/LP-1052)

Test documentation render

---

documentation/templates/documentation/index.html
documentation/tests/test_documentation_rendering.py
documentation/urls.py
documentation/views.py

I merged https://github.com/code-dot-org/curriculumbuilder/pull/234 into a random branch instead of master. This is the same thing just going to merge to master.

Docs landing take2

---

templates/cdo_base.html

I needed a more specific selector to access the documentation content on Code Studio in UI tests.

Add class to easily access documentation in code studio ui test

---

curricula/admin.py

I added a note to the UnitStandards admin page explaining how to import them into code studio. Clicking the link takes you to the code studio standards import admin page in a new tab.
- [jira](https://codedotorg.atlassian.net/browse/LP-1159?atlOrigin=eyJpIjoiYjcyYzk2YjE2YTc4NDhmMjhmYWY5NmNjZWJjZTA0NTMiLCJwIjoiaiJ9)

Add note about importing UnitStandards to Code Studio

---

lessons/migrations/0047_auto_20200402_1718.py
lessons/models.py

Migration to add creative_commons_image field to lesson model
- [jira](https://codedotorg.atlassian.net/browse/LP-1283?atlOrigin=eyJpIjoiZGE4YWM2OWQ3YjljNGY0ZTllYzNkYjIzNzJlYzcxZWEiLCJwIjoiaiJ9)

Migration to add creative commons license image to lessons model

---

package.json

Update this dependency to the version that should be able to run on heroku.
- [jira](https://codedotorg.atlassian.net/browse/LP-1473)
Tested by rebuilding npm dependencies locally

upgrade generate-pdf-scripts version

---

lessons/migrations/0048_lesson_code_studio_url.py

See https://github.com/code-dot-org/curriculumbuilder/pull/298 for context.

migration to add code_studio_url to lesson model

---

i18n/management/crowdin.py

I forgot that we actually need them on the local filesystem for the sake of the restoration process.
Followup to https://github.com/code-dot-org/curriculumbuilder/pull/306 and https://github.com/code-dot-org/curriculumbuilder/pull/307

Undo the optimization which downloaded files directly to S3

---

curriculumBuilder/settings.py

See https://github.com/code-dot-org/code-dot-org/pull/37001 for context
n/a

add a comment warning about the hacky dependency we have on the LANGUAGES setting

---

curriculumBuilder/settings.py

Add Brazilian Portuguese (pt-br) to the Curriculum Builder sync.

Add Brazilian Portuguese

---

curriculumBuilder/settings.py

Add Arabic and French

---

curricula/serializers.py
curricula/urls.py
curricula/views.py

#318 serialized unit / chapter / lesson / activity. This PR adds a url to download the result as json.

add url to export unit for import into code studio

---

curricula/serializers.py

include chapter title and description when exporting cb units

---

curricula/serializers.py

needed for https://github.com/code-dot-org/code-dot-org/pull/37845

export show_calendar field on Unit object

---

curricula/serializers.py

Example output:
```
{
"title": "Safety in My Online Neighborhood",
"number": 1,
"student_desc": "Learn how to go places safely online.",
"teacher_desc": "This lesson was originally created by Common Sense Education. [Learn more.](https://www.commonsense.org/education/digital-citizenship/curriculum)\r\n\r\nThe power of the internet allows students to experience and visit places they might not be able to see in person. But, just like traveling in the real world, it's important to be safe when traveling online. On this virtual field trip, kids can practice staying safe on online adventures.",
"activities": [
...
],
"objectives": [
{
"name": "Discover that the internet can be used to visit faraway places and learn new things."
},
{
"name": "Compare how staying safe online is similar to …
```

Export objectives, prep, and cs_content (purpose)

---

curricula/serializers.py

[Jira](https://codedotorg.atlassian.net/browse/PLAT-595)
- [spec]()
- [jira]()

Export assessment opportunities on lessons

---

i18n/management/commands/publish_i18n.py

*Bug* - The `publish_i18n` step of the i18n sync in CurriculumBuilder is not producing and translated files.
*Cause* - `pool.imap_unordered` is not a synchronous call, so work was getting queued up but the code never waited for the work to finish before ending the script.
*Fix* - Use `pool.map` which is a synchronous call. The translated content for a language will be completed before moving onto the next language.
* Configured `publish_i18n` to write the HTML files to my local disk and confirmed that there are now translations in all the languages.

Fixing the parallel processing in the publish_i18n step

---

curricula/serializers.py

We will be importing vocab into levelbuilder soon so we need a serializer for vocab!
- [spec]()
- [jira]()

Add and use VocabExportSerializer

---

i18n/SETUP.md

Adding documentation for successfully running the i18n sync locally in Curriculum Builder
- [spec]()
- [jira]()

setup documentation for the i18n sync in CB

---

curricula/serializers.py

Add Blocks to export serializer for lessons. 
Part of work on [PLAT-357](https://codedotorg.atlassian.net/browse/PLAT-357)

Export lesson-block associations to allow importing to levelbuilder

---

i18n/management/commands/i18n_sync_down.py

I noticed in the #curriculumbuilder Slack channel, that sometimes Slack starts throttling the i18n-sync messages because we are publishing too many. This PR looks to aggregate some of the message spam that happens right before Slack starts throttling.
The throttling is a problem because if an error occurs, we can't see what was logged.
Here is a screenshot from the Slack channel when the i18n-sync messages suddenly stop:
* Ran `debug=true python manage.py i18n_sync_down` locally

Aggregating some sync-down Slack messages so we reduce our API usage

---

curricula/templates/curricula/csf_unit.html
curricula/templates/curricula/partials/code_studio_pull_through/code_studio.html
curricula/templates/curricula/partials/code_studio_pull_through/contained_level.html
curricula/templates/curricula/partials/code_studio_pull_through/level_bubble_choice_parent.html
curricula/templates/curricula/partials/code_studio_pull_through/level_contents.html
curricula/templates/curricula/partials/code_studio_pull_through/level_contents_sublevel.html
curricula/templates/curricula/partials/code_studio_pull_through/level_mini_rubric.html
curricula/templates/curricula/partials/code_studio_pull_through/level_numbered_tab.html
curricula/templates/curricula/partials/code_studio_pull_through/level_numbered_tab_sublevel.html
curricula/templates/curricula/partials/code_studio_pull_through/level_sfmd_contents.html

Adding raw strings in the Code Studio pull through to our translation pipeline
- [spec]()
- [jira]()

Pull through translatability

---

static/css/common.css

Adds a style rule to style sessions with the keyword asynchronous as green. This is used by virtual summer workshops. 
Note: I could not get CB to start up locally for me but since this is such a small change I'm going to avoid debugging my CB set up for now so sorry no screenshot.

Add a style rule for a new keyword: asynchronous

---

static/css/common.css

Missed a couple places for adding css rules for keywords in the last PR

Needed to add a couple more CSS rules for async keyword

---

documentation/serializers.py
documentation/urls.py
documentation/views.py

Export block docs for consumption by code studio!
- [spec]()
- [jira]()

Add URL endpoint to export block docs

---

documentation/serializers.py

Just a small update to BlockExportSerializer to export the category the block is in as well.
- [spec]()
- [jira]()

Add category name to BlockExportSerializer
